name: My Actions
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - run: python my_script.py
    - run: pip install pylint
    - run: pylint **/*.py
  